app = "capstone-cicd-REPLACE_ME"   # <- change to a unique name
primary_region = "iad"             # choose your nearest region

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
